--- 
title: "Statistical rethinking"
author: "Bob"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

A golem (goh-lem) is a clay robot from Jewish folklore, constructed from dust and fire
and water. It is brought to life by inscribing emet, Hebrew for “truth,” on its brow. Animated
by truth, but lacking free will, a golem always does exactly what it is told. This is lucky,
because the golem is incredibly powerful, able to withstand and accomplish more than its
creators could. However, its obedience also brings danger, as careless instructions or unex-
pected events can turn a golem against its makers. Its abundance of power is matched by its
lack of wisdom.

# Statistical Golems
There are many kinds of statistical models. Whenever someone deploys even a simple
statistical procedure, like a classical t-test, she is deploying a small golem that will obediently
carry out an exact calculation, performing it the same way (nearly 2 ) every time, without
complaint. Nearly every branch of science relies upon the senses of statistical golems. In
many cases, it is no longer possible to even measure phenomena of interest, without making
use of a model. To measure the strength of natural selection or the speed of a neutrino or
the number of species in the Amazon, we must use models. The golem is a prosthesis, doing
the measuring for us, performing impressive calculations, finding patterns where none are
obvious.
